### PR TITLE
fix: Quote file paths in calls to ffmpeg

### LINKED ISSUE #131: Bug Report: Filenames with spaces break ffmpeg calls
### About me

This bug report is filed on behalf of the BBC

### Observed Behavior

A file with a space in the name / path breaks the ffmpeg calls
Package manager correctly checks that the file exists but fails at the scanning / thumbnail stages

```json
{
    "label": "AppContainer",
    "level": "warn",
    "message": "App \"appContainer0_15\" (worker.exe): [WorkerAgent] Worker \"appContainer0_15\" stopped job 94, (dca8e020f9216ef28edbad96f27dc6a95601d01b_deepscan), due to error: (0): Error: Command failed: ffprobe.exe -hide_banner -i D:\\Media\\File withSpaces.mxf -show_streams -show_format -print_format json\nArgument 'withSpaces.mxf' provided as input filename, but 'D:\\Media\\File' was already specified.\r\n, Error: Command failed: ffprobe.exe -hide_banner -i D:\\Media\\File withSpaces.mxf -show_streams -show_format -print_format json\nArgument 'withSpaces.mxf' provided as input filename, but 'D:\\Media\\File' was already specified.\r\n\n at ChildProcess.exithandler (node:child_process:398:12)\n at ChildProcess.emit (node:events:527:28)\n at maybeClose (node:internal/child_process:1092:16)\n at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)",
    "timestamp": "2024-02-02T10:47:02.033Z"
}
```

### Expected Behavior

Filenames with spaces should be handled correctly. (Presumably the args need to be wrapped in quotes?)

### Version

release51

### Severity / Impact

Thumbnails are not being generated for some clip names but Package Manager is identifying that the clips exist so it's not a major blocker, just annoying.

### PR DESCRIPTION
**Pull request by PeterC89**
## About Me

The pull request is posted on behalf of the BBC.

## Type of Contribution

This is a: Bug fix

## Current Behavior

File paths with spaces in break ffmpeg calls

## New Behavior

~~File paths are enclosed in quotes (think I got them all)~~
File paths are escaped depending on platform

## Other Information
Fixes #131 

## Status

- [X] PR is ready to be reviewed.
- [X] The functionality has been tested by the author.
- [x] Relevant unit tests has been added / updated.
- [ ] Relevant documentation (code comments, [system documentation](https://nrkno.github.io/sofie-core/)) has been added / updated.

### CODE REVIEW

**Comment by Julusian** [comment]
This needs some testing on linux, I am pretty sure that we have just removed the quotes because having them was an issue on linux https://github.com/nrkno/sofie-package-manager/pull/86

**Comment by nytamin** [comment]
I did a local test in Windows to verify that this fix works there. All good.
We'll wait for a test in Linux before merging.

**Review by nytamin — APPROVED** [review]

**Comment by Julusian** [comment]
```
@single-app/app: {"label":"AppContainer","level":"warn","message":"App \"appContainer0_0\" (worker): [WorkerAgent] Worker \"appContainer0_0\" stopped job 1, (8f5796ea6bea0e7381c17c8f781e55a483d507c2_preview), due to error: (0): Error: Command failed: ffprobe -hide_banner -i \"/home/julus/Projects/package_manager_test/target/WIPE.mov\" -show_streams -show_format -print_format json\n\"/home/julus/Projects/package_manager_test/target/WIPE.mov\": No such file or directory\n, Error: Command failed: ffprobe -hide_banner -i \"/home/julus/Projects/package_manager_test/target/WIPE.mov\" -show_streams -show_format -print_format json\n\"/home/julus/Projects/package_manager_test/target/WIPE.mov\": No such file or directory\n\n    at ChildProcess.exithandler (node:child_process:422:12)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2024-02-02T15:11:14.070Z"}
```
or reformatted:
```
Error: Command failed: ffprobe -hide_banner -i "/home/julus/Projects/package_manager_test/target/WIPE.mov" -show_streams -show_format -print_format json
"/home/julus/Projects/package_manager_test/target/WIPE.mov": No such file or directory
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
```

**Comment by Julusian** [comment]
Without this change, using files with spaces works fine.

Interestingly, with this change the file does get copied correctly still, but any calls with ffmpeg appear to fail

**Comment by PeterC89** [comment]
@Julusian @nytamin Changed it so quotes are only added on Windows

**Comment by Julusian** [comment]
@PeterC89 could you put that into a helper function, to make it less duplicated and clearer as to why it is done.

I am currently working on writing a couple of basic unit tests which will help guard against this, and I've found another couple of cases of issues with quotes

**Comment by PeterC89** [comment]
@Julusian Done, I've also made it so it escapes spaces on non-Windows platforms with a `\ ` but I'm not sure if that will break things?

**Comment by Julusian** [comment]
No linux doesn't appear to like that.
I've finished writing my tests, if you rebase onto https://github.com/nrkno/sofie-package-manager/pull/133 then the tests in github actions will be able to tell you if everything works.  
That branch currently has a lot of errors on windows, because of the bug you have found

**Comment by PeterC89** [comment]
@Julusian @nytamin This PR is probably ready now having gotten some time to track down the last unquoted calls

**Review by Julusian — APPROVED** [review]

**Comment by Julusian** [comment]
Thanks!
I've had to manually merge this https://github.com/nrkno/sofie-package-manager/commit/6625790206d9f48d859da35087c158a40ed213ce as I wanted to squash my changes which this was based on (I should have done that squash earlier)

**Comment by PeterC89** [comment]
Thanks @Julusian
Unfortunately this still appears to be broken on the live system.
Would you be able to do a build please just to make sure I'm not doing something daft on my local build?

**Pull request closed without merging**
